apiVersion: v1
kind: Service
metadata:
  name: event-bus
spec:
  type: NodePort
  selector:
    app: event-bus
  ports:
    - name: http
      protocol: TCP
      port: 4005
      targetPort: 4005
      nodePort: 30014
