apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cart
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cart
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.cart.service.type }}
  ports:
    - port: {{ .Values.cart.service.port }}
      targetPort: {{ .Values.cart.port }}
      nodePort: {{ .Values.cart.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-cart
    app.kubernetes.io/instance: {{ .Release.Name }}
