apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cart
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cart.port }}
      targetPort: {{ .Values.cart.port }}
  selector:
    app: {{ .Release.Name }}-cart
