apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-catalog
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-catalog
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.catalog.service.type }}
  ports:
    - port: {{ .Values.catalog.service.port }}
      targetPort: {{ .Values.catalog.port }}
      nodePort: {{ .Values.catalog.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-catalog
    app.kubernetes.io/instance: {{ .Release.Name }}
