apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-customer
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.customer.port }}
      targetPort: {{ .Values.customer.port }}
  selector:
    app: {{ .Release.Name }}-customer
