apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-eventbus
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-eventbus
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.eventbus.service.type }}
  ports:
    - port: {{ .Values.eventbus.service.port }}
      targetPort: {{ .Values.eventbus.port }}
      nodePort: {{ .Values.eventbus.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-eventbus
    app.kubernetes.io/instance: {{ .Release.Name }}
