apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: {{ .Values.ingressService.nodePort }}
