apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-order
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.order.service.type }}
  ports:
    - port: {{ .Values.order.service.port }}
      targetPort: {{ .Values.order.port }}
      nodePort: {{ .Values.order.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-order
    app.kubernetes.io/instance: {{ .Release.Name }}
