apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - name: http
      protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30011
