adminUser: admin
adminPassword: admin

service:
  type: NodePort
  port: 80
  nodePort: 30090  

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://192.168.178.122:30091
