apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: webshop
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        # ← DIESE drei Zeilen brauchst Du unbedingt:
        - name: POSTGRES_USER
          value: "piData"
        - name: POSTGRES_PASSWORD
          value: "senta"
        - name: POSTGRES_DB
          value: "pidb"
        # entferne die EVENT_BUS_URL und DATABASE_URL hier!
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: local-path
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
