name: Build & Publish

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0         
          persist-credentials: true  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

      - name: Build & Push cart-service
        uses: docker/build-push-action@v6
        with:
          context: cart-service
          file: cart-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/cart-service:${{ github.sha }}

      - name: Build & Push catalog-service
        uses: docker/build-push-action@v6
        with:
          context: catalog-service
          file: catalog-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/catalog-service:${{ github.sha }}

      - name: Build & Push customer-service
        uses: docker/build-push-action@v6
        with:
          context: customer-service
          file: customer-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/customer-service:${{ github.sha }}

      - name: Build & Push order-service
        uses: docker/build-push-action@v6
        with:
          context: order-service
          file: order-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/order-service:${{ github.sha }}

      - name: Build & Push event-service
        uses: docker/build-push-action@v6
        with:
          context: event-service
          file: event-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/event-service:${{ github.sha }}

      - name: Bump Helm Chart Image Tags
        run: |
          yq eval -i ".frontend.image.tag   = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
          yq eval -i ".cart.image.tag       = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
          yq eval -i ".catalog.image.tag    = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
          yq eval -i ".customer.image.tag   = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
          yq eval -i ".order.image.tag      = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
          yq eval -i ".eventbus.image.tag   = \"${GITHUB_SHA}\"" helm/webshop/values.yaml
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Commit Chart Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          # Hol erst remote; stash unsere Änderungen automatisch
          git pull --rebase origin main --autostash
          # Stage & commit nur, wenn values.yaml wirklich anders ist
          git add helm/webshop/values.yaml
          git diff --quiet --cached || git commit -m "ci: bump helm images to ${GITHUB_SHA}"
          git push origin main
