name: Build & Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/webshop:${{ github.sha }}

      - name: Bump Helm Chart Image Tag
        run: |
          sed -i "s|^\(\s*tag:\s*\).*|\1\"${{ github.sha }}\"|" helm/webshop/values.yaml

      - name: Commit Chart Update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/webshop/values.yaml
          git diff --quiet --cached || git commit -m "ci: bump helm image to ${{ github.sha }}"
          git push
